<script lang="ts">
  import windmill from "./windmill.svg?raw"
  import { onMount } from "svelte"

  onMount(() => {
    let svgStroke = document.getElementById("stroke")
    let svgBackground = document.getElementById("background")
    // @ts-ignore
    var svg = new Walkway({
      selector: "#windmill",
      duration: 5000,
      easing: "easeInQuart",
    })
    svgStroke?.setAttribute("stroke", "#fff6e0")
    svg.draw()
    setTimeout(() => {
      if (svgBackground) svgBackground.style.fill = "#01322a"
    }, 2500)
  })
</script>

<div class="wrapper">
  <div class="windmill">{@html windmill}</div>
  <div class="bottom">
    <p class="small">
      Installing clean power generation can save you thousands annually, and help bring down the
      amount of pollution generated by power plants.
    </p>
    <h1 class="beeg">
      Switching to <span class="c2">clean</span> energy <i class="c1">saves money</i>
    </h1>
  </div>
</div>

<style lang="scss">
  .windmill {
    width: 1000px;
    max-width: 100vw;
    margin-right: 50px;
    @media (max-aspect-ratio: 3/4) {
      margin-right: 15px;
    }
    @media (max-width: 1200px) {
      max-width: 90vw;
    }
  }

  .wrapper {
    width: 100%;
    height: 90vh;
    max-height: 1000px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    @media (max-aspect-ratio: 3/4) {
      height: max-content;
    }
    .bottom {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      width: 100%;
      .small {
        max-width: 55%;
        animation: bottom-fade 0.5s 4s forwards;
        opacity: 0;
      }
      .beeg {
        text-align: center;
        width: fit-content;
        animation: bottom-fade 0.5s 5s forwards;
        opacity: 0;
      }
      @media (max-aspect-ratio: 3/4) {
        flex-direction: column-reverse;
        .small {
          max-width: none;
          animation-delay: 5s;
        }
        .beeg {
          animation-delay: 4s;
        }
      }
    }
  }

  @keyframes bottom-fade {
    0% {
      transform: translateY(40px);
      opacity: 0;
    }
    100% {
      transform: translateX(0);
      opacity: 1;
    }
  }
</style>
