<script>
  import MultiPanel from "$lib/components/sections/MultiPanel/MultiPanel.svelte"
  import SinglePanel from "$lib/components/sections/SinglePanel/SinglePanel.svelte"
  import Saos from "saos"
</script>

<div id="page">
  <Saos once={true}><SinglePanel /></Saos>
  <p class="more-info">&emsp;&emsp;If you live somewhere that gets sun very often, like in L.A. or somewhere in Texas, solar power may pay itself off very quickly, either by tax incentives or just by offsetting the power bill. On average, solar power costs $25,000 to install and get running. There is, if eligible, a 30% federal tax credit that contributes to taxes for the next several years which comes out to $7,500 at that price. Assuming the national average price per Kilowatt-hour (kWh) of 16 cents1 and kWh per household per month of 8772, that brings the average electricity bill to $140.32. The average amount of energy generated by a single solar panel is 350 Watts per hour at peak efficiency3, but depending on the weather, temperature of the panel, etc. it will likely perform at around 22% efficiency4. Assuming a low-end average group of 15 panels needed to power a single household3, this comes out to a real world output of 776.16 kWh. That is a saving of 88.5% or $124.19 per month. This means that after tax reductions, it’ll pay itself off after about 12 years. Considering these panels tend to last 20 years with little degrading at all1, that’s a pretty good deal!</p>
  <Saos once={true}><MultiPanel /></Saos>
</div>

<style>
  .more-info{
    font-size: 12pt;
    font-weight: 250;
  }
</style>
