<script>
  import MultiPanel from "$lib/components/sections/MultiPanel/MultiPanel.svelte"
  import SinglePanel from "$lib/components/sections/SinglePanel/SinglePanel.svelte"
  import Saos from "saos"
</script>

<div id="page">
  <Saos once={true}><SinglePanel /></Saos>
  <!-- TODO: Fact check -->
  <!-- TODO: Re-add important info -->
  <!-- TODO: Add animation -->
  <div class="quote">
    <div class="wrap-around">
      Installing solar panels costs an average of <i>$25,000.</i>
    </div>
    <p>
      While the initial investment is quite steep, clean energy initiatives from the US government
      offer substantial tax breaks. In combination with the power savings from the panels
      themselves, you'll likely start seeing returns on your investment within 2 to 4 years.
    </p>
  </div>
  <!-- <p>
    While installing solar panels costs an average of $25,000, once that price is paid, you can get 30% of that bill back off of your taxes in addition to the money off of the power bill. If we use the averages across the U.S., if you had 15 panels, you could be saving <span class="c2">over $100 every month!</span> If you have more panels or use less power, you could even sell some of that energy back to the power company to <i>make</i> money rather than just <i>saving</i> it.
  </p> -->
  <Saos once={true}><MultiPanel /></Saos>
  <div class="quote">
    <div class="wrap-around right">Proident id veniam irure cillum irure nulla.</div>
    Veniam cupidatat velit ut exercitation nisi amet id officia nulla Lorem deserunt quis. Ipsum amet
    ut consectetur pariatur ea ad dolore aute sit enim excepteur do voluptate eiusmod. Id velit fugiat
    magna sint ea. Sunt ullamco anim non nostrud deserunt nulla.
  </div>
  <!-- TODO: Rephrase this: -->
  <!-- <p>
    According to <a href="https://www.energysage.com/solar/solar-panel-output/">energysage.com</a>, 15 panels is on the lower end of the averages. If you use the higher range of said averages, you'd get 25 panels which could be generating a little over 45 kWh per day! That's enough that you realistically <i>could</i> start selling back electricity!
  </p> -->

  <!-- <p class="more-info">&emsp;&emsp;If you live somewhere that gets sun very often, like in L.A. or somewhere in Texas, solar power may pay itself off very quickly, either by tax incentives or just by offsetting the power bill. On average, solar power costs $25,000 to install and get running. There is, if eligible, a 30% federal tax credit that contributes to taxes for the next several years which comes out to $7,500 at that price. Assuming the national average price per Kilowatt-hour (kWh) of 16 cents1 and kWh per household per month of 8772, that brings the average electricity bill to $140.32. The average amount of energy generated by a single solar panel is 350 Watts per hour at peak efficiency3, but depending on the weather, temperature of the panel, etc. it will likely perform at around 22% efficiency4. Assuming a low-end average group of 15 panels needed to power a single household3, this comes out to a real world output of 776.16 kWh. That is a saving of 88.5% or $124.19 per month. This means that after tax reductions, it’ll pay itself off after about 12 years. Considering these panels tend to last 20 years with little degrading at all1, that’s a pretty good deal!</p> -->
</div>

<!-- ! DELETE THIS AFTER YOU HAVE SEEN THE JOKE -->
<style lang="scss">
  code {
    padding: 10px;
    border: 1px solid #74c7ec;
    border-radius: 20px;
    display: block;
    margin-top: 20px;
    .indent {
      padding-left: 2em;
    }
    font-family: "FiraCode Nerd Font", "Fira Code";
    font-size: 12pt;
    background-color: #1e1e2e;
    color: #cdd6f4;
    i {
      font-style: normal;
      &.teal {
        color: #94e2d5;
      }
      &.blue {
        color: #89b4fa;
      }
      &.yellow {
        color: #f9e2af;
      }
      &.green {
        color: #a6e3a1;
      }
    }
  }
</style>
