<script lang="ts">
  import windmill from "$lib/svg/windmill.svg?raw"
  import { onMount } from "svelte"

  onMount(() => {
    let svgStroke = document.getElementById("stroke")
    let svgBackground = document.getElementById("background")
    // @ts-ignore
    var svg = new Walkway({
      selector: "#windmill",
      duration: 5000,
      easing: "easeInQuart",
    })
    svgStroke?.setAttribute("stroke", "#fff6e0")
    svg.draw()
    setTimeout(() => {
      if (svgBackground) svgBackground.style.fill = "#01322a"
    }, 2500)
  })
</script>

<div class="wrapper">
  <div class="windmill">{@html windmill}</div>
  <div class="bottom">
    <p>
      Installing clean power generation can save you thousands<br />annually, and help bring down
      the amount of pollution<br />generated by power plants.
    </p>
    <h1>Switching to <span class="c2">clean</span><br />energy <i class="c1">saves money</i></h1>
  </div>
</div>

<style lang="scss">
  .windmill {
    width: 1000px;
    max-width: 90vw;
    margin-right: 50px;
  }

  .wrapper {
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    .bottom {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      width: 100%;
      p {
        max-width: 55%;
      }
      h1 {
        text-align: center;
        width: fit-content;
      }
    }
  }
</style>
