<script lang="ts">
  import windmill from "$lib/svg/windmill.svg?raw"
  import Saos from "saos"
  import { onMount } from "svelte"

  onMount(() => {
    let svgStroke = document.getElementById("stroke")
    let svgBackground = document.getElementById("background")
    // @ts-ignore
    var svg = new Walkway({
      selector: "#windmill",
      duration: 5000,
      easing: "easeInQuart",
    })
    svgStroke?.setAttribute("stroke", "#fff6e0")
    svg.draw()
    setTimeout(() => {
      if (svgBackground) svgBackground.style.fill = "#01322a"
    }, 2500)
  })
</script>

<div class="wrapper">
  <div class="windmill">{@html windmill}</div>
  <div class="bottom">
    <div class="small">
      <Saos animation="banner-bottom-fade 4.5s" once={true}>
        <p>
          Installing clean power generation can save you thousands<br />annually, and help bring
          down the amount of pollution<br />generated by power plants.
        </p>
      </Saos>
    </div>
    <div class="beeg">
      <Saos animation="banner-bottom-fade-long 5.5s" once={true}>
        <h1>
          Switching to <span class="c2">clean</span><br />energy <i class="c1">saves money</i>
        </h1>
      </Saos>
    </div>
  </div>
</div>

<style lang="scss">
  .windmill {
    width: 1000px;
    max-width: 90vw;
    margin-right: 50px;
  }

  .wrapper {
    width: 100%;
    height: 100vh;
    max-height: 1000px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    .bottom {
      display: flex;
      flex-direction: row;
      justify-content: space-between;
      width: 100%;
      .small {
        max-width: 55%;
      }
      .beeg {
        text-align: center;
        width: fit-content;
      }
    }
  }

  @keyframes -global-banner-bottom-fade {
    0% {
      transform: translateY(40px);
      opacity: 0;
    }
    88.88% {
      transform: translateY(40px);
      opacity: 0;
    }
    100% {
      transform: translateX(0);
      opacity: 1;
    }
  }
  @keyframes -global-banner-bottom-fade-long {
    0% {
      transform: translateY(40px);
      opacity: 0;
    }
    90.90% {
      transform: translateY(40px);
      opacity: 0;
    }
    100% {
      transform: translateX(0);
      opacity: 1;
    }
  }
</style>
